version: '3.8'

services:
  ios:
    build: .
    privileged: true
    environment:
      - USBMUXD_HOST=192.168.48.146
      - USBMUXD_PORT=31543
      - USBMUXD_SOCKET=/var/run/usbmuxd
    tmpfs:
      - /tmp/usbmuxd
#      - /var/run/usbmuxd